{
  data: [
    {
      away_image_url: "https://img.abiosgaming.com/competitors/AGO-Rogue-logo.png",
      away_team: "AGO ROGUE",
      away_team_id: 3108,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/Eintracht-Spandau-teamlogo.png",
      home_team: "Eintracht Spandau",
      home_team_id: 17446,
      id: 482445,
      live_enabled: true,
      main_market_id: 15781263,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 33996278,
            market_id: 15781263,
            max_bet: "174.00",
            name: "Eintracht Spandau",
            price: "1.82",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 33996279,
            market_id: 15781263,
            max_bet: "174.00",
            name: "AGO ROGUE",
            price: "1.82",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15781263,
        match_id: 482445,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Eintracht Spandau v AGO ROGUE",
      num_bets_placed: 39,
      num_markets: 17,
      start_time: "2022-04-17T15:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_red_team.png",
      away_team: "Team Phantasma",
      away_team_id: 8016,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/X7_Esportslogo_square-teamlogo.png.png",
      home_team: "X7 Esports",
      home_team_id: 14605,
      id: 482473,
      live_enabled: true,
      main_market_id: 15781583,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 33996900,
            market_id: 15781583,
            max_bet: "261.00",
            name: "X7 Esports",
            price: "1.07",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 33996901,
            market_id: 15781583,
            max_bet: "29.00",
            name: "Team Phantasma",
            price: "6.00",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15781583,
        match_id: 482473,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "X7 Esports v Team Phantasma",
      num_bets_placed: 60,
      num_markets: 1,
      start_time: "2022-04-17T16:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://d1dewv214im63w.cloudfront.net/teams/bifrost-logo.png",
      away_team: "Bifrost",
      away_team_id: 3154,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://d1dewv214im63w.cloudfront.net/teams/team-esca-gaming-logo.png",
      home_team: "Team ESCA Gaming",
      home_team_id: 9376,
      id: 482500,
      live_enabled: true,
      main_market_id: 15781966,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 33997657,
            market_id: 15781966,
            max_bet: "58.00",
            name: "Team ESCA Gaming",
            price: "2.88",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 33997658,
            market_id: 15781966,
            max_bet: "261.00",
            name: "Bifrost",
            price: "1.33",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15781966,
        match_id: 482500,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Team ESCA Gaming v Bifrost",
      num_bets_placed: 53,
      num_markets: 17,
      start_time: "2022-04-17T17:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://img.abiosgaming.com/competitors/crvena-zvezda-czd-logo.png",
      away_team: "Crvena Zvezda",
      away_team_id: 1232,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/Vitality-team-2018-true-logo.png",
      home_team: "Vitality.Bee",
      home_team_id: 113,
      id: 482546,
      live_enabled: true,
      main_market_id: 15783590,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34001703,
            market_id: 15783590,
            max_bet: "261.00",
            name: "Vitality.Bee",
            price: "1.10",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34001704,
            market_id: 15783590,
            max_bet: "29.00",
            name: "Crvena Zvezda",
            price: "5.10",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15783590,
        match_id: 482546,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Vitality.Bee v Crvena Zvezda",
      num_bets_placed: 26,
      num_markets: 17,
      start_time: "2022-04-17T18:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://img.abiosgaming.com/competitors/GamersLegion-logo.png",
      away_team: "GamerLegion",
      away_team_id: 2520,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/team-Karmine-Corp.png",
      home_team: "Karmine Corp",
      home_team_id: 9358,
      id: 482576,
      live_enabled: true,
      main_market_id: 15783775,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34002048,
            market_id: 15783775,
            max_bet: "261.00",
            name: "Karmine Corp",
            price: "1.33",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34002049,
            market_id: 15783775,
            max_bet: "58.00",
            name: "Team GamerLegion",
            price: "2.88",
            raw_status: "open",
            short_name: "GamerLegion",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15783775,
        match_id: 482576,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Karmine Corp v GamerLegion",
      num_bets_placed: 32,
      num_markets: 17,
      start_time: "2022-04-17T19:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://img.abiosgaming.com/casters/C9-Cloud9-logo-no-text.png",
      away_team: "Cloud9",
      away_team_id: 391,
      best_of: 5,
      competition_id: 2763,
      competition_name: "LCS",
      displayed_format: "BO5",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/Evil-Geniuses-new-teamlogo.png",
      home_team: "Evil Geniuses",
      home_team_id: 3076,
      id: 482594,
      live_enabled: true,
      main_market_id: 15784001,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34002493,
            market_id: 15784001,
            max_bet: "174.00",
            name: "Evil Geniuses",
            price: "2.46",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34002494,
            market_id: 15784001,
            max_bet: "493.00",
            name: "Cloud9",
            price: "1.52",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15784001,
        match_id: 482594,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Evil Geniuses v Cloud9",
      num_bets_placed: 23,
      num_markets: 108,
      start_time: "2022-04-17T19:30:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://img.abiosgaming.com/competitors/Team-BDS.png.png",
      away_team: "Team BDS Academy",
      away_team_id: 17458,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/Fnatic-TQ-teamlogo.png",
      home_team: "Fnatic TQ",
      home_team_id: 17439,
      id: 482604,
      live_enabled: true,
      main_market_id: 15784682,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34003858,
            market_id: 15784682,
            max_bet: "232.00",
            name: "Fnatic TQ",
            price: "1.60",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34003859,
            market_id: 15784682,
            max_bet: "116.00",
            name: "Team BDS Academy",
            price: "2.10",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15784682,
        match_id: 482604,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Fnatic TQ v Team BDS Academy",
      num_bets_placed: 59,
      num_markets: 17,
      start_time: "2022-04-17T20:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://d1dewv214im63w.cloudfront.net/teams/ldlc-ol-logo.png",
      away_team: "LDLC OL",
      away_team_id: 3077,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/Bisons-Eclub-teamlogo.png",
      home_team: "BISONS ECLUB",
      home_team_id: 17437,
      id: 484989,
      live_enabled: false,
      main_market_id: 15837893,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34122765,
            market_id: 15837893,
            max_bet: "58.00",
            name: "BISONS ECLUB",
            price: "2.88",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34122766,
            market_id: 15837893,
            max_bet: "261.00",
            name: "LDLC OL",
            price: "1.33",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15837893,
        match_id: 484989,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "BISONS ECLUB v LDLC OL",
      num_bets_placed: 15,
      num_markets: 1,
      start_time: "2022-04-21T15:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://img.abiosgaming.com/competitors/Unicorns-of-Love.png",
      away_team: "Unicorns Of Love Sexy Edition",
      away_team_id: 1722,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_blue_team.png",
      home_team: "Atleta Esports",
      home_team_id: 17547,
      id: 485026,
      live_enabled: false,
      main_market_id: 15838745,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34124450,
            market_id: 15838745,
            max_bet: "29.00",
            name: "Atleta Esports",
            price: "3.75",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34124451,
            market_id: 15838745,
            max_bet: "261.00",
            name: "Unicorns Of Love Sexy Edition",
            price: "1.20",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15838745,
        match_id: 485026,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Atleta Esports v Unicorns Of Love Sexy Edition",
      num_bets_placed: 87,
      num_markets: 1,
      start_time: "2022-04-21T16:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_red_team.png",
      away_team: "Atleta Esports",
      away_team_id: 17547,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://d1dewv214im63w.cloudfront.net/teams/ldlc-ol-logo.png",
      home_team: "LDLC OL",
      home_team_id: 3077,
      id: 485074,
      live_enabled: false,
      main_market_id: 15839760,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34126477,
            market_id: 15839760,
            max_bet: "261.00",
            name: "LDLC OL",
            price: "1.12",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34126478,
            market_id: 15839760,
            max_bet: "29.00",
            name: "Atleta Esports",
            price: "4.80",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15839760,
        match_id: 485074,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "LDLC OL v Atleta Esports",
      num_bets_placed: 19,
      num_markets: 1,
      start_time: "2022-04-21T17:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://img.abiosgaming.com/competitors/Bisons-Eclub-teamlogo.png",
      away_team: "BISONS ECLUB",
      away_team_id: 17437,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/Unicorns-of-Love.png",
      home_team: "Unicorns Of Love Sexy Edition",
      home_team_id: 1722,
      id: 485115,
      live_enabled: false,
      main_market_id: 15840720,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34128470,
            market_id: 15840720,
            max_bet: "261.00",
            name: "Unicorns Of Love Sexy Edition",
            price: "1.46",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34128471,
            market_id: 15840720,
            max_bet: "87.00",
            name: "BISONS ECLUB",
            price: "2.40",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15840720,
        match_id: 485115,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Unicorns Of Love Sexy Edition v BISONS ECLUB",
      num_bets_placed: 29,
      num_markets: 1,
      start_time: "2022-04-21T18:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://s3-eu-west-1.amazonaws.com/midnite.com/teams/placeholder_red_team.png",
      away_team: "Atleta Esports",
      away_team_id: 17547,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://img.abiosgaming.com/competitors/Bisons-Eclub-teamlogo.png",
      home_team: "BISONS ECLUB",
      home_team_id: 17437,
      id: 485144,
      live_enabled: false,
      main_market_id: 15840918,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34128844,
            market_id: 15840918,
            max_bet: "261.00",
            name: "BISONS ECLUB",
            price: "1.37",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34128845,
            market_id: 15840918,
            max_bet: "58.00",
            name: "Atleta Esports",
            price: "2.70",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15840918,
        match_id: 485144,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "BISONS ECLUB v Atleta Esports",
      num_bets_placed: 48,
      num_markets: 1,
      start_time: "2022-04-21T19:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://img.abiosgaming.com/competitors/Unicorns-of-Love.png",
      away_team: "Unicorns Of Love Sexy Edition",
      away_team_id: 1722,
      best_of: 1,
      competition_id: 2995,
      competition_name: "European Masters",
      displayed_format: "BO1",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://d1dewv214im63w.cloudfront.net/teams/ldlc-ol-logo.png",
      home_team: "LDLC OL",
      home_team_id: 3077,
      id: 485168,
      live_enabled: false,
      main_market_id: 15841129,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34129340,
            market_id: 15841129,
            max_bet: "261.00",
            name: "LDLC OL",
            price: "1.46",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34129341,
            market_id: 15841129,
            max_bet: "87.00",
            name: "Unicorns Of Love Sexy Edition",
            price: "2.40",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15841129,
        match_id: 485168,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "LDLC OL v Unicorns Of Love Sexy Edition",
      num_bets_placed: 32,
      num_markets: 1,
      start_time: "2022-04-21T20:00:00.000000Z",
      status: "upcoming",
      type: "match"
    },
    {
      away_image_url: "https://img.abiosgaming.com/competitors/Lowkey-teamlogo.png",
      away_team: "Team Secret",
      away_team_id: 1769,
      best_of: 5,
      competition_id: 2793,
      competition_name: "Vietnam Championship Series",
      displayed_format: "BO5",
      game_id: 4,
      game_name: "League of Legends",
      home_image_url: "https://d1dewv214im63w.cloudfront.net/teams/saigon-buffalo-logo.png",
      home_team: "Saigon Buffalo",
      home_team_id: 6649,
      id: 485573,
      live_enabled: false,
      main_market_id: 15854234,
      market: {
        contracts: [
          {
            display_order: 0,
            id: 34165943,
            market_id: 15854234,
            max_bet: "203.00",
            name: "Saigon Buffalo",
            price: "1.62",
            raw_status: "open",
            status: "open"
          },
          {
            display_order: 10,
            id: 34165944,
            market_id: 15854234,
            max_bet: "116.00",
            name: "Team Secret",
            price: "2.06",
            raw_status: "open",
            status: "open"
          }
        ],
        display_order: 0,
        id: 15854234,
        match_id: 485573,
        name: "Match Winner",
        popular: true,
        status: "open"
      },
      name: "Saigon Buffalo v Team Secret",
      num_bets_placed: 79,
      num_markets: 11,
      start_time: "2022-04-22T11:00:00.000000Z",
      status: "upcoming",
      type: "match"
    }
  ]
}